/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Marcos
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RolagemjScrollPane = new javax.swing.JScrollPane();
        PanelParaScrolljPanel = new javax.swing.JPanel();
        dadosDoSacadojPanel = new javax.swing.JPanel();
        nomeDoSacadojLabel = new javax.swing.JLabel();
        nomeDoSacadojTextField = new javax.swing.JTextField();
        CPFDoSacadojLabel = new javax.swing.JLabel();
        CPFDoSacadojTextField = new javax.swing.JTextField();
        enderecoDoSacadojPanel = new javax.swing.JPanel();
        UFDoSacadojLabel = new javax.swing.JLabel();
        UFDoSacadojTextField = new javax.swing.JTextField();
        LocalidadeDoSacadojLabel = new javax.swing.JLabel();
        localidadeDoSacadojTextField = new javax.swing.JTextField();
        CEPDoSacadojLabel = new javax.swing.JLabel();
        CEPDoSacadojTextField = new javax.swing.JTextField();
        bairroDoSacadojLabel = new javax.swing.JLabel();
        bairroDoSacadojTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        logradouroDoSacadojTextField = new javax.swing.JTextField();
        numeroDoSacadojLabel = new javax.swing.JLabel();
        numeroDoSacadojTextField = new javax.swing.JTextField();
        dadosDoTitulojPanel = new javax.swing.JPanel();
        numeroDoDocumentoDoTitulojLabel = new javax.swing.JLabel();
        numeroDoDocumentoDoTitulojTextField = new javax.swing.JTextField();
        nossoNumeroDoTitulojLabel = new javax.swing.JLabel();
        nossoNumeroDoTitulojTextField = new javax.swing.JTextField();
        digitoNossoNumeroDoTitulojLabel = new javax.swing.JLabel();
        digitoNossoNumeroDoTitulojTextField = new javax.swing.JTextField();
        valorDoTitulojLabel = new javax.swing.JLabel();
        valorDoTitulojTextField = new javax.swing.JTextField();
        dataDoDocumentoDoTitulojLabel = new javax.swing.JLabel();
        dataDoDocumentoDoTitulojTextField = new javax.swing.JTextField();
        dataDeVencimentoDoTitulojLabel = new javax.swing.JLabel();
        dataDeVencimentoDoTitulojTextField = new javax.swing.JTextField();
        tipoDeDocumentoDoTitulojLabel = new javax.swing.JLabel();
        tipoDeDocumentoDoTitulojTextField = new javax.swing.JTextField();
        aceiteDoTitulojLabel = new javax.swing.JLabel();
        aceiteDoTitulojTextField = new javax.swing.JTextField();
        descontoDoTitulojLabel = new javax.swing.JLabel();
        descontoDoTitulojTextField = new javax.swing.JTextField();
        deducaoDoTitulojLabel = new javax.swing.JLabel();
        deducaoDoTitulojTextField = new javax.swing.JTextField();
        moraDoTitulojLabel = new javax.swing.JLabel();
        moraDoTitulojTextField = new javax.swing.JTextField();
        acrescimoDoTitulojLabel = new javax.swing.JLabel();
        acrescimoDoTitulojTextField = new javax.swing.JTextField();
        valorCobradoDoTitulojLabel = new javax.swing.JLabel();
        valorCobredoDoTitulojTextField = new javax.swing.JTextField();
        dadosDoSacadoAvalistajPanel = new javax.swing.JPanel();
        nomeDoSacadoAvalistajLabel = new javax.swing.JLabel();
        nomeDoSacadoAvalistajTextField = new javax.swing.JTextField();
        CPFDoSacadoAvalistajLabel = new javax.swing.JLabel();
        CPFDoSacadoAvalistajTextField = new javax.swing.JTextField();
        enderecoDoSacadoAvalistaJPanel = new javax.swing.JPanel();
        UFDoSacadoAvalistajLabel = new javax.swing.JLabel();
        UFDoSacadoAvalistajTextField = new javax.swing.JTextField();
        localidadeDoSacadoAvalistajLabel = new javax.swing.JLabel();
        localidadeDoSacadoAvalistajTextField = new javax.swing.JTextField();
        CEPDoSacadoAvalistajLabel = new javax.swing.JLabel();
        CEPDoSacadoAvalistajTextField = new javax.swing.JTextField();
        bairroDoSacadoAvalistajLabel = new javax.swing.JLabel();
        bairroDoSacadoAvalistajTextField = new javax.swing.JTextField();
        logradouroDoSacadoAvalistajLabel = new javax.swing.JLabel();
        logradouroDoSacadoAvalistajTextField = new javax.swing.JTextField();
        numeroDoSacadoAvalistajLabel = new javax.swing.JLabel();
        numeroDoSacadoAvalistajTextField = new javax.swing.JTextField();
        DadosDoCedentejPanel = new javax.swing.JPanel();
        nomeDaEmpresajLabel = new javax.swing.JLabel();
        nomeDaEmpresajTextField = new javax.swing.JTextField();
        CNPJjLabel = new javax.swing.JLabel();
        CNPJjTextField = new javax.swing.JTextField();
        dadosDaContaBancariajPanel1 = new javax.swing.JPanel();
        bancoDaContaBancariaJLabel = new javax.swing.JLabel();
        bancoDaContaBancariajTextField = new javax.swing.JTextField();
        numeroDaContaDaContaBancariajLabel = new javax.swing.JLabel();
        numeroDaContaDaContaBancariajTextField = new javax.swing.JTextField();
        tiposDeCarteiraDaContaBancariajLabel = new javax.swing.JLabel();
        tipoDeCarteiraDaContaBancariajTextField = new javax.swing.JTextField();
        agenciaDaContaBancariaJPanel = new javax.swing.JPanel();
        nomeAgenciaDaContaBancariajLabel = new javax.swing.JLabel();
        nomeAgenciaDaContaBancariajTextField = new javax.swing.JTextField();
        numeroAgenciaDaContaBancariajLabel = new javax.swing.JLabel();
        numeroAgenciaDaContaBancariajTextField = new javax.swing.JTextField();
        dadosDoBoletojPanel = new javax.swing.JPanel();
        localDePagamentoDoBoletojLabel = new javax.swing.JLabel();
        localDePagamentoDoBoletojTextField = new javax.swing.JTextField();
        instrucaoAoSacadoDoBoletojLabel = new javax.swing.JLabel();
        instrucaoAoSacadoDoBoletojTextField = new javax.swing.JTextField();
        instrucao1DoBoletojLabel = new javax.swing.JLabel();
        instrucao1DoBoletoTextField = new javax.swing.JTextField();
        instrucao2DoBoletojLabel = new javax.swing.JLabel();
        instrucao2DoBoletoTextField = new javax.swing.JTextField();
        instrucao3DoBoletojLabel = new javax.swing.JLabel();
        instrucao3DoBoletoTextField = new javax.swing.JTextField();
        instrucao4DoBoletojLabel = new javax.swing.JLabel();
        instrucao4DoBoletoTextField = new javax.swing.JTextField();
        instrucao5DoBoletojLabel = new javax.swing.JLabel();
        instrucao5DoBoletoTextField = new javax.swing.JTextField();
        instrucao6DoBoletojLabel = new javax.swing.JLabel();
        instrucao6DoBoletoTextField = new javax.swing.JTextField();
        instrucao7DoBoletojLabel = new javax.swing.JLabel();
        instrucao7DoBoletoTextField = new javax.swing.JTextField();
        instrucao8DoBoletojLabel = new javax.swing.JLabel();
        instrucao8DoBoletoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dadosDoSacadojPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Sacado"));

        nomeDoSacadojLabel.setText("Nome");

        nomeDoSacadojTextField.setToolTipText("Digite o nome do Sacado");

        CPFDoSacadojLabel.setText("CPF");

        CPFDoSacadojTextField.setToolTipText("Digite o CPF do Sacado");

        enderecoDoSacadojPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        UFDoSacadojLabel.setText("UF");

        UFDoSacadojTextField.setToolTipText("Digite o UF do Sacado");

        LocalidadeDoSacadojLabel.setText("Localidade");

        localidadeDoSacadojTextField.setToolTipText("Digite a Localidade do Sacado");

        CEPDoSacadojLabel.setText("CEP");

        CEPDoSacadojTextField.setToolTipText("Digite o CEP do Sacado");

        bairroDoSacadojLabel.setText("Bairro");

        bairroDoSacadojTextField.setToolTipText("Digite o Bairro do Sacado");

        jLabel7.setText("Logradouro");

        logradouroDoSacadojTextField.setToolTipText("Digite o Logradouro do Sacado");

        numeroDoSacadojLabel.setText("Numero");

        numeroDoSacadojTextField.setToolTipText("Digite o Número do Sacado");

        javax.swing.GroupLayout enderecoDoSacadojPanelLayout = new javax.swing.GroupLayout(enderecoDoSacadojPanel);
        enderecoDoSacadojPanel.setLayout(enderecoDoSacadojPanelLayout);
        enderecoDoSacadojPanelLayout.setHorizontalGroup(
            enderecoDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoDoSacadojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enderecoDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enderecoDoSacadojPanelLayout.createSequentialGroup()
                        .addComponent(UFDoSacadojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UFDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecoDoSacadojPanelLayout.createSequentialGroup()
                        .addComponent(LocalidadeDoSacadojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(localidadeDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecoDoSacadojPanelLayout.createSequentialGroup()
                        .addComponent(CEPDoSacadojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CEPDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecoDoSacadojPanelLayout.createSequentialGroup()
                        .addComponent(bairroDoSacadojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bairroDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecoDoSacadojPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(logradouroDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecoDoSacadojPanelLayout.createSequentialGroup()
                        .addComponent(numeroDoSacadojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numeroDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        enderecoDoSacadojPanelLayout.setVerticalGroup(
            enderecoDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoDoSacadojPanelLayout.createSequentialGroup()
                .addGroup(enderecoDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UFDoSacadojLabel)
                    .addComponent(UFDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecoDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocalidadeDoSacadojLabel)
                    .addComponent(localidadeDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecoDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEPDoSacadojLabel)
                    .addComponent(CEPDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecoDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairroDoSacadojLabel)
                    .addComponent(bairroDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecoDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(logradouroDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(enderecoDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroDoSacadojLabel)
                    .addComponent(numeroDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout dadosDoSacadojPanelLayout = new javax.swing.GroupLayout(dadosDoSacadojPanel);
        dadosDoSacadojPanel.setLayout(dadosDoSacadojPanelLayout);
        dadosDoSacadojPanelLayout.setHorizontalGroup(
            dadosDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDoSacadojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeDoSacadojLabel)
                    .addComponent(CPFDoSacadojLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dadosDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPFDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
            .addGroup(dadosDoSacadojPanelLayout.createSequentialGroup()
                .addComponent(enderecoDoSacadojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dadosDoSacadojPanelLayout.setVerticalGroup(
            dadosDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDoSacadojPanelLayout.createSequentialGroup()
                .addGroup(dadosDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDoSacadojLabel)
                    .addComponent(nomeDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoSacadojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFDoSacadojLabel)
                    .addComponent(CPFDoSacadojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoDoSacadojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dadosDoTitulojPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Título"));
        dadosDoTitulojPanel.setToolTipText("");

        numeroDoDocumentoDoTitulojLabel.setText("Número do Documento");

        numeroDoDocumentoDoTitulojTextField.setToolTipText("Digite o Número do Documento Do Titulo");

        nossoNumeroDoTitulojLabel.setText("Nosso Número");

        nossoNumeroDoTitulojTextField.setToolTipText("Digite o Nosso Número");

        digitoNossoNumeroDoTitulojLabel.setText("Digito do Nosso Numero");

        digitoNossoNumeroDoTitulojTextField.setToolTipText("Digite o Titulo do Nosso Numero");

        valorDoTitulojLabel.setText("Valor");

        valorDoTitulojTextField.setToolTipText("");

        dataDoDocumentoDoTitulojLabel.setText("Data do Documento");

        dataDoDocumentoDoTitulojTextField.setToolTipText("");

        dataDeVencimentoDoTitulojLabel.setText("Data de Vencimento");

        dataDeVencimentoDoTitulojTextField.setToolTipText("");

        tipoDeDocumentoDoTitulojLabel.setText("Tipo de Documento");

        tipoDeDocumentoDoTitulojTextField.setToolTipText("");

        aceiteDoTitulojLabel.setText("Aceite");

        aceiteDoTitulojTextField.setToolTipText("");

        descontoDoTitulojLabel.setText("Desconto");

        descontoDoTitulojTextField.setToolTipText("");

        deducaoDoTitulojLabel.setText("Dedução");

        deducaoDoTitulojTextField.setToolTipText("");

        moraDoTitulojLabel.setText("Mora");

        moraDoTitulojTextField.setToolTipText("");

        acrescimoDoTitulojLabel.setText("Acréscimo");

        acrescimoDoTitulojTextField.setToolTipText("");

        valorCobradoDoTitulojLabel.setText("Valor Cobrado");

        valorCobredoDoTitulojTextField.setToolTipText("");

        javax.swing.GroupLayout dadosDoTitulojPanelLayout = new javax.swing.GroupLayout(dadosDoTitulojPanel);
        dadosDoTitulojPanel.setLayout(dadosDoTitulojPanelLayout);
        dadosDoTitulojPanelLayout.setHorizontalGroup(
            dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(numeroDoDocumentoDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numeroDoDocumentoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(nossoNumeroDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nossoNumeroDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(digitoNossoNumeroDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(digitoNossoNumeroDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(valorDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valorDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(dataDoDocumentoDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataDoDocumentoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(dataDeVencimentoDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dataDeVencimentoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(tipoDeDocumentoDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipoDeDocumentoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(aceiteDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceiteDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(descontoDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descontoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(deducaoDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deducaoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(moraDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moraDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(acrescimoDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(acrescimoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                        .addComponent(valorCobradoDoTitulojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valorCobredoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dadosDoTitulojPanelLayout.setVerticalGroup(
            dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDoTitulojPanelLayout.createSequentialGroup()
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroDoDocumentoDoTitulojLabel)
                    .addComponent(numeroDoDocumentoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nossoNumeroDoTitulojLabel)
                    .addComponent(nossoNumeroDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(digitoNossoNumeroDoTitulojLabel)
                    .addComponent(digitoNossoNumeroDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorDoTitulojLabel)
                    .addComponent(valorDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDoDocumentoDoTitulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataDoDocumentoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDeVencimentoDoTitulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataDeVencimentoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoDeDocumentoDoTitulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoDeDocumentoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceiteDoTitulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceiteDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descontoDoTitulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descontoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deducaoDoTitulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deducaoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moraDoTitulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moraDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acrescimoDoTitulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acrescimoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoTitulojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorCobradoDoTitulojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorCobredoDoTitulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        dadosDoSacadoAvalistajPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Sacado Avalista"));

        nomeDoSacadoAvalistajLabel.setText("Nome");

        nomeDoSacadoAvalistajTextField.setToolTipText("Digite");

        CPFDoSacadoAvalistajLabel.setText("CPF");

        CPFDoSacadoAvalistajTextField.setToolTipText("Digite");

        enderecoDoSacadoAvalistaJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        UFDoSacadoAvalistajLabel.setText("UF");

        UFDoSacadoAvalistajTextField.setToolTipText("Digite");

        localidadeDoSacadoAvalistajLabel.setText("Localidade");

        localidadeDoSacadoAvalistajTextField.setToolTipText("Digite");

        CEPDoSacadoAvalistajLabel.setText("CEP");

        CEPDoSacadoAvalistajTextField.setToolTipText("Digite");

        bairroDoSacadoAvalistajLabel.setText("Bairro");

        bairroDoSacadoAvalistajTextField.setToolTipText("Digite");

        logradouroDoSacadoAvalistajLabel.setText("Logradouro");

        logradouroDoSacadoAvalistajTextField.setToolTipText("Digite");

        numeroDoSacadoAvalistajLabel.setText("Numero");

        numeroDoSacadoAvalistajTextField.setToolTipText("Digite");

        javax.swing.GroupLayout enderecoDoSacadoAvalistaJPanelLayout = new javax.swing.GroupLayout(enderecoDoSacadoAvalistaJPanel);
        enderecoDoSacadoAvalistaJPanel.setLayout(enderecoDoSacadoAvalistaJPanelLayout);
        enderecoDoSacadoAvalistaJPanelLayout.setHorizontalGroup(
            enderecoDoSacadoAvalistaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createSequentialGroup()
                        .addComponent(UFDoSacadoAvalistajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UFDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createSequentialGroup()
                        .addComponent(localidadeDoSacadoAvalistajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(localidadeDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createSequentialGroup()
                        .addComponent(CEPDoSacadoAvalistajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CEPDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createSequentialGroup()
                        .addComponent(bairroDoSacadoAvalistajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bairroDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createSequentialGroup()
                        .addComponent(logradouroDoSacadoAvalistajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(logradouroDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createSequentialGroup()
                        .addComponent(numeroDoSacadoAvalistajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numeroDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        enderecoDoSacadoAvalistaJPanelLayout.setVerticalGroup(
            enderecoDoSacadoAvalistaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createSequentialGroup()
                .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UFDoSacadoAvalistajLabel)
                    .addComponent(UFDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localidadeDoSacadoAvalistajLabel)
                    .addComponent(localidadeDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEPDoSacadoAvalistajLabel)
                    .addComponent(CEPDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairroDoSacadoAvalistajLabel)
                    .addComponent(bairroDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logradouroDoSacadoAvalistajLabel)
                    .addComponent(logradouroDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(enderecoDoSacadoAvalistaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroDoSacadoAvalistajLabel)
                    .addComponent(numeroDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout dadosDoSacadoAvalistajPanelLayout = new javax.swing.GroupLayout(dadosDoSacadoAvalistajPanel);
        dadosDoSacadoAvalistajPanel.setLayout(dadosDoSacadoAvalistajPanelLayout);
        dadosDoSacadoAvalistajPanelLayout.setHorizontalGroup(
            dadosDoSacadoAvalistajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDoSacadoAvalistajPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosDoSacadoAvalistajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeDoSacadoAvalistajLabel)
                    .addComponent(CPFDoSacadoAvalistajLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dadosDoSacadoAvalistajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPFDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(dadosDoSacadoAvalistajPanelLayout.createSequentialGroup()
                .addComponent(enderecoDoSacadoAvalistaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dadosDoSacadoAvalistajPanelLayout.setVerticalGroup(
            dadosDoSacadoAvalistajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDoSacadoAvalistajPanelLayout.createSequentialGroup()
                .addGroup(dadosDoSacadoAvalistajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDoSacadoAvalistajLabel)
                    .addComponent(nomeDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dadosDoSacadoAvalistajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPFDoSacadoAvalistajLabel)
                    .addComponent(CPFDoSacadoAvalistajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enderecoDoSacadoAvalistaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DadosDoCedentejPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cedente"));

        nomeDaEmpresajLabel.setText("Nome da Empresa");

        nomeDaEmpresajTextField.setToolTipText("Digite");

        CNPJjLabel.setText("CNPJ");

        CNPJjTextField.setToolTipText("Digite");

        javax.swing.GroupLayout DadosDoCedentejPanelLayout = new javax.swing.GroupLayout(DadosDoCedentejPanel);
        DadosDoCedentejPanel.setLayout(DadosDoCedentejPanelLayout);
        DadosDoCedentejPanelLayout.setHorizontalGroup(
            DadosDoCedentejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosDoCedentejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DadosDoCedentejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DadosDoCedentejPanelLayout.createSequentialGroup()
                        .addComponent(CNPJjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CNPJjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DadosDoCedentejPanelLayout.createSequentialGroup()
                        .addComponent(nomeDaEmpresajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomeDaEmpresajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DadosDoCedentejPanelLayout.setVerticalGroup(
            DadosDoCedentejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosDoCedentejPanelLayout.createSequentialGroup()
                .addGroup(DadosDoCedentejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeDaEmpresajLabel)
                    .addComponent(nomeDaEmpresajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DadosDoCedentejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNPJjLabel)
                    .addComponent(CNPJjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        dadosDaContaBancariajPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Conta Bancária"));

        bancoDaContaBancariaJLabel.setText("Banco");

        bancoDaContaBancariajTextField.setToolTipText("Digite");

        numeroDaContaDaContaBancariajLabel.setText("Numero da Conta");

        numeroDaContaDaContaBancariajTextField.setToolTipText("Digite");

        tiposDeCarteiraDaContaBancariajLabel.setText("Tipo de Cateira");

        tipoDeCarteiraDaContaBancariajTextField.setToolTipText("Digite");

        agenciaDaContaBancariaJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Agencia"));

        nomeAgenciaDaContaBancariajLabel.setText("Nome");

        nomeAgenciaDaContaBancariajTextField.setToolTipText("Digite");

        numeroAgenciaDaContaBancariajLabel.setText("Número");

        numeroAgenciaDaContaBancariajTextField.setToolTipText("Digite");

        javax.swing.GroupLayout agenciaDaContaBancariaJPanelLayout = new javax.swing.GroupLayout(agenciaDaContaBancariaJPanel);
        agenciaDaContaBancariaJPanel.setLayout(agenciaDaContaBancariaJPanelLayout);
        agenciaDaContaBancariaJPanelLayout.setHorizontalGroup(
            agenciaDaContaBancariaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agenciaDaContaBancariaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agenciaDaContaBancariaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agenciaDaContaBancariaJPanelLayout.createSequentialGroup()
                        .addComponent(nomeAgenciaDaContaBancariajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomeAgenciaDaContaBancariajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agenciaDaContaBancariaJPanelLayout.createSequentialGroup()
                        .addComponent(numeroAgenciaDaContaBancariajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numeroAgenciaDaContaBancariajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        agenciaDaContaBancariaJPanelLayout.setVerticalGroup(
            agenciaDaContaBancariaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agenciaDaContaBancariaJPanelLayout.createSequentialGroup()
                .addGroup(agenciaDaContaBancariaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeAgenciaDaContaBancariajLabel)
                    .addComponent(nomeAgenciaDaContaBancariajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(agenciaDaContaBancariaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroAgenciaDaContaBancariajLabel)
                    .addComponent(numeroAgenciaDaContaBancariajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout dadosDaContaBancariajPanel1Layout = new javax.swing.GroupLayout(dadosDaContaBancariajPanel1);
        dadosDaContaBancariajPanel1.setLayout(dadosDaContaBancariajPanel1Layout);
        dadosDaContaBancariajPanel1Layout.setHorizontalGroup(
            dadosDaContaBancariajPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDaContaBancariajPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosDaContaBancariajPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dadosDaContaBancariajPanel1Layout.createSequentialGroup()
                        .addComponent(numeroDaContaDaContaBancariajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numeroDaContaDaContaBancariajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDaContaBancariajPanel1Layout.createSequentialGroup()
                        .addComponent(bancoDaContaBancariaJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bancoDaContaBancariajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDaContaBancariajPanel1Layout.createSequentialGroup()
                        .addComponent(tiposDeCarteiraDaContaBancariajLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipoDeCarteiraDaContaBancariajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(agenciaDaContaBancariaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dadosDaContaBancariajPanel1Layout.setVerticalGroup(
            dadosDaContaBancariajPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDaContaBancariajPanel1Layout.createSequentialGroup()
                .addGroup(dadosDaContaBancariajPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bancoDaContaBancariaJLabel)
                    .addComponent(bancoDaContaBancariajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDaContaBancariajPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroDaContaDaContaBancariajLabel)
                    .addComponent(numeroDaContaDaContaBancariajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDaContaBancariajPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiposDeCarteiraDaContaBancariajLabel)
                    .addComponent(tipoDeCarteiraDaContaBancariajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agenciaDaContaBancariaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dadosDoBoletojPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Boleto"));

        localDePagamentoDoBoletojLabel.setText("Local de Pagamento");

        localDePagamentoDoBoletojTextField.setToolTipText("Digite o Local de Pagamento");

        instrucaoAoSacadoDoBoletojLabel.setText("Instrução ao Sacado");

        instrucaoAoSacadoDoBoletojTextField.setToolTipText("Digite");

        instrucao1DoBoletojLabel.setText("Instrução 1");

        instrucao1DoBoletoTextField.setToolTipText("Digite");

        instrucao2DoBoletojLabel.setText("Instrução 2");

        instrucao2DoBoletoTextField.setToolTipText("Digite");

        instrucao3DoBoletojLabel.setText("Instrução 3");

        instrucao3DoBoletoTextField.setToolTipText("Digite");

        instrucao4DoBoletojLabel.setText("Instrução 4");

        instrucao4DoBoletoTextField.setToolTipText("Digite");

        instrucao5DoBoletojLabel.setText("Instrução 5");

        instrucao5DoBoletoTextField.setToolTipText("Digite");

        instrucao6DoBoletojLabel.setText("Instrução 6");

        instrucao6DoBoletoTextField.setToolTipText("Digite");

        instrucao7DoBoletojLabel.setText("Instrução 7");

        instrucao7DoBoletoTextField.setToolTipText("Digite");

        instrucao8DoBoletojLabel.setText("Instrução 8");

        instrucao8DoBoletoTextField.setToolTipText("Digite");

        javax.swing.GroupLayout dadosDoBoletojPanelLayout = new javax.swing.GroupLayout(dadosDoBoletojPanel);
        dadosDoBoletojPanel.setLayout(dadosDoBoletojPanelLayout);
        dadosDoBoletojPanelLayout.setHorizontalGroup(
            dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDoBoletojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosDoBoletojPanelLayout.createSequentialGroup()
                        .addComponent(instrucao1DoBoletojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(instrucao1DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoBoletojPanelLayout.createSequentialGroup()
                        .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dadosDoBoletojPanelLayout.createSequentialGroup()
                                .addComponent(localDePagamentoDoBoletojLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(localDePagamentoDoBoletojTextField))
                            .addGroup(dadosDoBoletojPanelLayout.createSequentialGroup()
                                .addComponent(instrucaoAoSacadoDoBoletojLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(instrucaoAoSacadoDoBoletojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dadosDoBoletojPanelLayout.createSequentialGroup()
                        .addComponent(instrucao2DoBoletojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(instrucao2DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoBoletojPanelLayout.createSequentialGroup()
                        .addComponent(instrucao3DoBoletojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(instrucao3DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoBoletojPanelLayout.createSequentialGroup()
                        .addComponent(instrucao4DoBoletojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(instrucao4DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosDoBoletojPanelLayout.createSequentialGroup()
                        .addComponent(instrucao5DoBoletojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(instrucao5DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dadosDoBoletojPanelLayout.createSequentialGroup()
                        .addComponent(instrucao6DoBoletojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(instrucao6DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosDoBoletojPanelLayout.createSequentialGroup()
                        .addComponent(instrucao7DoBoletojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(instrucao7DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dadosDoBoletojPanelLayout.createSequentialGroup()
                        .addComponent(instrucao8DoBoletojLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(instrucao8DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dadosDoBoletojPanelLayout.setVerticalGroup(
            dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dadosDoBoletojPanelLayout.createSequentialGroup()
                .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localDePagamentoDoBoletojLabel)
                    .addComponent(localDePagamentoDoBoletojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrucaoAoSacadoDoBoletojLabel)
                    .addComponent(instrucaoAoSacadoDoBoletojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrucao1DoBoletojLabel)
                    .addComponent(instrucao1DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrucao2DoBoletojLabel)
                    .addComponent(instrucao2DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrucao3DoBoletojLabel)
                    .addComponent(instrucao3DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrucao4DoBoletojLabel)
                    .addComponent(instrucao4DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrucao5DoBoletojLabel)
                    .addComponent(instrucao5DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrucao6DoBoletojLabel)
                    .addComponent(instrucao6DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrucao7DoBoletojLabel)
                    .addComponent(instrucao7DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dadosDoBoletojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(instrucao8DoBoletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dadosDoBoletojPanelLayout.createSequentialGroup()
                        .addComponent(instrucao8DoBoletojLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))))
        );

        javax.swing.GroupLayout PanelParaScrolljPanelLayout = new javax.swing.GroupLayout(PanelParaScrolljPanel);
        PanelParaScrolljPanel.setLayout(PanelParaScrolljPanelLayout);
        PanelParaScrolljPanelLayout.setHorizontalGroup(
            PanelParaScrolljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelParaScrolljPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PanelParaScrolljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelParaScrolljPanelLayout.createSequentialGroup()
                        .addComponent(dadosDoSacadojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dadosDoSacadoAvalistajPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelParaScrolljPanelLayout.createSequentialGroup()
                        .addGroup(PanelParaScrolljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dadosDoTitulojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DadosDoCedentejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelParaScrolljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dadosDaContaBancariajPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dadosDoBoletojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        PanelParaScrolljPanelLayout.setVerticalGroup(
            PanelParaScrolljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelParaScrolljPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelParaScrolljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dadosDoSacadojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadosDoSacadoAvalistajPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelParaScrolljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelParaScrolljPanelLayout.createSequentialGroup()
                        .addComponent(dadosDaContaBancariajPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dadosDoBoletojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelParaScrolljPanelLayout.createSequentialGroup()
                        .addComponent(dadosDoTitulojPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DadosDoCedentejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        RolagemjScrollPane.setViewportView(PanelParaScrolljPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RolagemjScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RolagemjScrollPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CEPDoSacadoAvalistajLabel;
    private javax.swing.JTextField CEPDoSacadoAvalistajTextField;
    private javax.swing.JLabel CEPDoSacadojLabel;
    private javax.swing.JTextField CEPDoSacadojTextField;
    private javax.swing.JLabel CNPJjLabel;
    private javax.swing.JTextField CNPJjTextField;
    private javax.swing.JLabel CPFDoSacadoAvalistajLabel;
    private javax.swing.JTextField CPFDoSacadoAvalistajTextField;
    private javax.swing.JLabel CPFDoSacadojLabel;
    private javax.swing.JTextField CPFDoSacadojTextField;
    private javax.swing.JPanel DadosDoCedentejPanel;
    private javax.swing.JLabel LocalidadeDoSacadojLabel;
    private javax.swing.JPanel PanelParaScrolljPanel;
    private javax.swing.JScrollPane RolagemjScrollPane;
    private javax.swing.JLabel UFDoSacadoAvalistajLabel;
    private javax.swing.JTextField UFDoSacadoAvalistajTextField;
    private javax.swing.JLabel UFDoSacadojLabel;
    private javax.swing.JTextField UFDoSacadojTextField;
    private javax.swing.JLabel aceiteDoTitulojLabel;
    private javax.swing.JTextField aceiteDoTitulojTextField;
    private javax.swing.JLabel acrescimoDoTitulojLabel;
    private javax.swing.JTextField acrescimoDoTitulojTextField;
    private javax.swing.JPanel agenciaDaContaBancariaJPanel;
    private javax.swing.JLabel bairroDoSacadoAvalistajLabel;
    private javax.swing.JTextField bairroDoSacadoAvalistajTextField;
    private javax.swing.JLabel bairroDoSacadojLabel;
    private javax.swing.JTextField bairroDoSacadojTextField;
    private javax.swing.JLabel bancoDaContaBancariaJLabel;
    private javax.swing.JTextField bancoDaContaBancariajTextField;
    private javax.swing.JPanel dadosDaContaBancariajPanel1;
    private javax.swing.JPanel dadosDoBoletojPanel;
    private javax.swing.JPanel dadosDoSacadoAvalistajPanel;
    private javax.swing.JPanel dadosDoSacadojPanel;
    private javax.swing.JPanel dadosDoTitulojPanel;
    private javax.swing.JLabel dataDeVencimentoDoTitulojLabel;
    private javax.swing.JTextField dataDeVencimentoDoTitulojTextField;
    private javax.swing.JLabel dataDoDocumentoDoTitulojLabel;
    private javax.swing.JTextField dataDoDocumentoDoTitulojTextField;
    private javax.swing.JLabel deducaoDoTitulojLabel;
    private javax.swing.JTextField deducaoDoTitulojTextField;
    private javax.swing.JLabel descontoDoTitulojLabel;
    private javax.swing.JTextField descontoDoTitulojTextField;
    private javax.swing.JLabel digitoNossoNumeroDoTitulojLabel;
    private javax.swing.JTextField digitoNossoNumeroDoTitulojTextField;
    private javax.swing.JPanel enderecoDoSacadoAvalistaJPanel;
    private javax.swing.JPanel enderecoDoSacadojPanel;
    private javax.swing.JTextField instrucao1DoBoletoTextField;
    private javax.swing.JLabel instrucao1DoBoletojLabel;
    private javax.swing.JTextField instrucao2DoBoletoTextField;
    private javax.swing.JLabel instrucao2DoBoletojLabel;
    private javax.swing.JTextField instrucao3DoBoletoTextField;
    private javax.swing.JLabel instrucao3DoBoletojLabel;
    private javax.swing.JTextField instrucao4DoBoletoTextField;
    private javax.swing.JLabel instrucao4DoBoletojLabel;
    private javax.swing.JTextField instrucao5DoBoletoTextField;
    private javax.swing.JLabel instrucao5DoBoletojLabel;
    private javax.swing.JTextField instrucao6DoBoletoTextField;
    private javax.swing.JLabel instrucao6DoBoletojLabel;
    private javax.swing.JTextField instrucao7DoBoletoTextField;
    private javax.swing.JLabel instrucao7DoBoletojLabel;
    private javax.swing.JTextField instrucao8DoBoletoTextField;
    private javax.swing.JLabel instrucao8DoBoletojLabel;
    private javax.swing.JLabel instrucaoAoSacadoDoBoletojLabel;
    private javax.swing.JTextField instrucaoAoSacadoDoBoletojTextField;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel localDePagamentoDoBoletojLabel;
    private javax.swing.JTextField localDePagamentoDoBoletojTextField;
    private javax.swing.JLabel localidadeDoSacadoAvalistajLabel;
    private javax.swing.JTextField localidadeDoSacadoAvalistajTextField;
    private javax.swing.JTextField localidadeDoSacadojTextField;
    private javax.swing.JLabel logradouroDoSacadoAvalistajLabel;
    private javax.swing.JTextField logradouroDoSacadoAvalistajTextField;
    private javax.swing.JTextField logradouroDoSacadojTextField;
    private javax.swing.JLabel moraDoTitulojLabel;
    private javax.swing.JTextField moraDoTitulojTextField;
    private javax.swing.JLabel nomeAgenciaDaContaBancariajLabel;
    private javax.swing.JTextField nomeAgenciaDaContaBancariajTextField;
    private javax.swing.JLabel nomeDaEmpresajLabel;
    private javax.swing.JTextField nomeDaEmpresajTextField;
    private javax.swing.JLabel nomeDoSacadoAvalistajLabel;
    private javax.swing.JTextField nomeDoSacadoAvalistajTextField;
    private javax.swing.JLabel nomeDoSacadojLabel;
    private javax.swing.JTextField nomeDoSacadojTextField;
    private javax.swing.JLabel nossoNumeroDoTitulojLabel;
    private javax.swing.JTextField nossoNumeroDoTitulojTextField;
    private javax.swing.JLabel numeroAgenciaDaContaBancariajLabel;
    private javax.swing.JTextField numeroAgenciaDaContaBancariajTextField;
    private javax.swing.JLabel numeroDaContaDaContaBancariajLabel;
    private javax.swing.JTextField numeroDaContaDaContaBancariajTextField;
    private javax.swing.JLabel numeroDoDocumentoDoTitulojLabel;
    private javax.swing.JTextField numeroDoDocumentoDoTitulojTextField;
    private javax.swing.JLabel numeroDoSacadoAvalistajLabel;
    private javax.swing.JTextField numeroDoSacadoAvalistajTextField;
    private javax.swing.JLabel numeroDoSacadojLabel;
    private javax.swing.JTextField numeroDoSacadojTextField;
    private javax.swing.JTextField tipoDeCarteiraDaContaBancariajTextField;
    private javax.swing.JLabel tipoDeDocumentoDoTitulojLabel;
    private javax.swing.JTextField tipoDeDocumentoDoTitulojTextField;
    private javax.swing.JLabel tiposDeCarteiraDaContaBancariajLabel;
    private javax.swing.JLabel valorCobradoDoTitulojLabel;
    private javax.swing.JTextField valorCobredoDoTitulojTextField;
    private javax.swing.JLabel valorDoTitulojLabel;
    private javax.swing.JTextField valorDoTitulojTextField;
    // End of variables declaration//GEN-END:variables
}
